// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/roles/service.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/roles/service.go -destination=src/api/internal/roles/mock_service_test.go -package=roles Service
//

// Package roles is a generated GoMock package.
package roles

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockService) AssignRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockServiceMockRecorder) AssignRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockService)(nil).AssignRole), ctx, userID, roleID)
}

// GetRoleByID mocks base method.
func (m *MockService) GetRoleByID(ctx context.Context, roleID uuid.UUID) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, roleID)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockServiceMockRecorder) GetRoleByID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockService)(nil).GetRoleByID), ctx, roleID)
}

// GetRoleByName mocks base method.
func (m *MockService) GetRoleByName(ctx context.Context, name string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockServiceMockRecorder) GetRoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockService)(nil).GetRoleByName), ctx, name)
}

// ListRoles mocks base method.
func (m *MockService) ListRoles(ctx context.Context) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockServiceMockRecorder) ListRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockService)(nil).ListRoles), ctx)
}

// LoadUserRoles mocks base method.
func (m *MockService) LoadUserRoles(ctx context.Context, userID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserRoles", ctx, userID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserRoles indicates an expected call of LoadUserRoles.
func (mr *MockServiceMockRecorder) LoadUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserRoles", reflect.TypeOf((*MockService)(nil).LoadUserRoles), ctx, userID)
}

// RemoveRole mocks base method.
func (m *MockService) RemoveRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockServiceMockRecorder) RemoveRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockService)(nil).RemoveRole), ctx, userID, roleID)
}

// MockRepositoryAccess is a mock of RepositoryAccess interface.
type MockRepositoryAccess struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryAccessMockRecorder
	isgomock struct{}
}

// MockRepositoryAccessMockRecorder is the mock recorder for MockRepositoryAccess.
type MockRepositoryAccessMockRecorder struct {
	mock *MockRepositoryAccess
}

// NewMockRepositoryAccess creates a new mock instance.
func NewMockRepositoryAccess(ctrl *gomock.Controller) *MockRepositoryAccess {
	mock := &MockRepositoryAccess{ctrl: ctrl}
	mock.recorder = &MockRepositoryAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryAccess) EXPECT() *MockRepositoryAccessMockRecorder {
	return m.recorder
}

// AssignRoleToUser mocks base method.
func (m *MockRepositoryAccess) AssignRoleToUser(ctx context.Context, tx any, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, tx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockRepositoryAccessMockRecorder) AssignRoleToUser(ctx, tx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockRepositoryAccess)(nil).AssignRoleToUser), ctx, tx, userID, roleID)
}

// GetRoleIDByName mocks base method.
func (m *MockRepositoryAccess) GetRoleIDByName(ctx context.Context, tx any, name string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleIDByName", ctx, tx, name)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleIDByName indicates an expected call of GetRoleIDByName.
func (mr *MockRepositoryAccessMockRecorder) GetRoleIDByName(ctx, tx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleIDByName", reflect.TypeOf((*MockRepositoryAccess)(nil).GetRoleIDByName), ctx, tx, name)
}
