// Code generated by MockGen. DO NOT EDIT.
// Source: src/workers/internal/transactions/service.go
//
// Generated by this command:
//
//	mockgen -source=src/workers/internal/transactions/service.go -destination=src/workers/internal/transactions/mock_evaluator_test.go -package=transactions RuleEvaluator
//

// Package transactions is a generated GoMock package.
package transactions

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleEvaluator is a mock of RuleEvaluator interface.
type MockRuleEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockRuleEvaluatorMockRecorder
	isgomock struct{}
}

// MockRuleEvaluatorMockRecorder is the mock recorder for MockRuleEvaluator.
type MockRuleEvaluatorMockRecorder struct {
	mock *MockRuleEvaluator
}

// NewMockRuleEvaluator creates a new mock instance.
func NewMockRuleEvaluator(ctrl *gomock.Controller) *MockRuleEvaluator {
	mock := &MockRuleEvaluator{ctrl: ctrl}
	mock.recorder = &MockRuleEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleEvaluator) EXPECT() *MockRuleEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockRuleEvaluator) Evaluate(ctx context.Context, event models.Event) (*models.TransactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, event)
	ret0, _ := ret[0].(*models.TransactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockRuleEvaluatorMockRecorder) Evaluate(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockRuleEvaluator)(nil).Evaluate), ctx, event)
}
