// Code generated by MockGen. DO NOT EDIT.
// Source: queue_service.go

package queue

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisPopper is a mock of RedisPopper interface
type MockRedisPopper struct {
	ctrl     *gomock.Controller
	recorder *MockRedisPopperMockRecorder
}

// MockRedisPopperMockRecorder is the mock recorder for MockRedisPopper
type MockRedisPopperMockRecorder struct {
	mock *MockRedisPopper
}

// NewMockRedisPopper creates a new mock instance
func NewMockRedisPopper(ctrl *gomock.Controller) *MockRedisPopper {
	mock := &MockRedisPopper{ctrl: ctrl}
	mock.recorder = &MockRedisPopperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRedisPopper) EXPECT() *MockRedisPopperMockRecorder {
	return m.recorder
}

// BRPop mocks base method
func (m *MockRedisPopper) BRPop(ctx context.Context, timeout time.Duration, keys ...string) *redis.StringSliceCmd {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, timeout}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BRPop", varargs...)
	ret0, _ := ret[0].(*redis.StringSliceCmd)
	return ret0
}

// BRPop indicates an expected call of BRPop
func (mr *MockRedisPopperMockRecorder) BRPop(ctx, timeout interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, timeout}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BRPop", reflect.TypeOf((*MockRedisPopper)(nil).BRPop), varargs...)
}
