// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_tokenrevoke_service_test.go -package=auth TokenRevokeService

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenRevokeService is a mock of TokenRevokeService interface.
type MockTokenRevokeService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRevokeServiceMockRecorder
	isgomock struct{}
}

// MockTokenRevokeServiceMockRecorder is the mock recorder for MockTokenRevokeService.
type MockTokenRevokeServiceMockRecorder struct {
	mock *MockTokenRevokeService
}

// NewMockTokenRevokeService creates a new mock instance.
func NewMockTokenRevokeService(ctrl *gomock.Controller) *MockTokenRevokeService {
	mock := &MockTokenRevokeService{ctrl: ctrl}
	mock.recorder = &MockTokenRevokeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRevokeService) EXPECT() *MockTokenRevokeServiceMockRecorder {
	return m.recorder
}

// IsTokenRevoked mocks base method.
func (m *MockTokenRevokeService) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenRevoked", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenRevoked indicates an expected call of IsTokenRevoked.
func (mr *MockTokenRevokeServiceMockRecorder) IsTokenRevoked(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenRevoked", reflect.TypeOf((*MockTokenRevokeService)(nil).IsTokenRevoked), ctx, token)
}

// IsUserTokensRevoked mocks base method.
func (m *MockTokenRevokeService) IsUserTokensRevoked(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserTokensRevoked", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserTokensRevoked indicates an expected call of IsUserTokensRevoked.
func (mr *MockTokenRevokeServiceMockRecorder) IsUserTokensRevoked(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserTokensRevoked", reflect.TypeOf((*MockTokenRevokeService)(nil).IsUserTokensRevoked), ctx, userID)
}

// RevokeAllUserTokens mocks base method.
func (m *MockTokenRevokeService) RevokeAllUserTokens(ctx context.Context, userID string, tokenExpiry time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserTokens", ctx, userID, tokenExpiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserTokens indicates an expected call of RevokeAllUserTokens.
func (mr *MockTokenRevokeServiceMockRecorder) RevokeAllUserTokens(ctx, userID, tokenExpiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserTokens", reflect.TypeOf((*MockTokenRevokeService)(nil).RevokeAllUserTokens), ctx, userID, tokenExpiry)
}

// RevokeToken mocks base method.
func (m *MockTokenRevokeService) RevokeToken(ctx context.Context, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenRevokeServiceMockRecorder) RevokeToken(ctx, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenRevokeService)(nil).RevokeToken), ctx, token, expiresAt)
}
