// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/transactions/service.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/transactions/service.go -destination=src/api/internal/transactions/mock_queue_test.go -package=transactions
//

// Package transactions is a generated GoMock package.
package transactions

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetTransaction mocks base method.
func (m *MockService) GetTransaction(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockServiceMockRecorder) GetTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockService)(nil).GetTransaction), ctx, id)
}

// ListTransactions mocks base method.
func (m *MockService) ListTransactions(ctx context.Context, limit, offset int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockServiceMockRecorder) ListTransactions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockService)(nil).ListTransactions), ctx, limit, offset)
}

// ProcessTransaction mocks base method.
func (m *MockService) ProcessTransaction(ctx context.Context, event models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTransaction", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTransaction indicates an expected call of ProcessTransaction.
func (mr *MockServiceMockRecorder) ProcessTransaction(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTransaction", reflect.TypeOf((*MockService)(nil).ProcessTransaction), ctx, event)
}

// MockQueuePusher is a mock of QueuePusher interface.
type MockQueuePusher struct {
	ctrl     *gomock.Controller
	recorder *MockQueuePusherMockRecorder
	isgomock struct{}
}

// MockQueuePusherMockRecorder is the mock recorder for MockQueuePusher.
type MockQueuePusherMockRecorder struct {
	mock *MockQueuePusher
}

// NewMockQueuePusher creates a new mock instance.
func NewMockQueuePusher(ctrl *gomock.Controller) *MockQueuePusher {
	mock := &MockQueuePusher{ctrl: ctrl}
	mock.recorder = &MockQueuePusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueuePusher) EXPECT() *MockQueuePusherMockRecorder {
	return m.recorder
}

// LPush mocks base method.
func (m *MockQueuePusher) LPush(ctx context.Context, key string, values ...any) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LPush", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// LPush indicates an expected call of LPush.
func (mr *MockQueuePusherMockRecorder) LPush(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockQueuePusher)(nil).LPush), varargs...)
}
