// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/transactions/service.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/transactions/service.go -destination=src/api/internal/transactions/mock_transactionservice_test.go -package=transactions -mock_names=Service=MockTransactionService Service
//

// Package transactions is a generated GoMock package.
package transactions

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of Service interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
	isgomock struct{}
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// ApproveTransaction mocks base method.
func (m *MockTransactionService) ApproveTransaction(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveTransaction", ctx, id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveTransaction indicates an expected call of ApproveTransaction.
func (mr *MockTransactionServiceMockRecorder) ApproveTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveTransaction", reflect.TypeOf((*MockTransactionService)(nil).ApproveTransaction), ctx, id)
}

// GetTransaction mocks base method.
func (m *MockTransactionService) GetTransaction(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionServiceMockRecorder) GetTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionService)(nil).GetTransaction), ctx, id)
}

// ListTransactions mocks base method.
func (m *MockTransactionService) ListTransactions(ctx context.Context, limit, offset int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockTransactionServiceMockRecorder) ListTransactions(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockTransactionService)(nil).ListTransactions), ctx, limit, offset)
}

// ListTransactionsWithFilter mocks base method.
func (m *MockTransactionService) ListTransactionsWithFilter(ctx context.Context, filter TransactionFilter, limit, offset int) ([]models.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsWithFilter", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactionsWithFilter indicates an expected call of ListTransactionsWithFilter.
func (mr *MockTransactionServiceMockRecorder) ListTransactionsWithFilter(ctx, filter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsWithFilter", reflect.TypeOf((*MockTransactionService)(nil).ListTransactionsWithFilter), ctx, filter, limit, offset)
}

// ProcessTransaction mocks base method.
func (m *MockTransactionService) ProcessTransaction(ctx context.Context, event models.Event) (*asynq.TaskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTransaction", ctx, event)
	ret0, _ := ret[0].(*asynq.TaskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessTransaction indicates an expected call of ProcessTransaction.
func (mr *MockTransactionServiceMockRecorder) ProcessTransaction(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTransaction", reflect.TypeOf((*MockTransactionService)(nil).ProcessTransaction), ctx, event)
}

// RejectTransaction mocks base method.
func (m *MockTransactionService) RejectTransaction(ctx context.Context, id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectTransaction", ctx, id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectTransaction indicates an expected call of RejectTransaction.
func (mr *MockTransactionServiceMockRecorder) RejectTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectTransaction", reflect.TypeOf((*MockTransactionService)(nil).RejectTransaction), ctx, id)
}

// MockTaskEnqueuer is a mock of TaskEnqueuer interface.
type MockTaskEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockTaskEnqueuerMockRecorder
	isgomock struct{}
}

// MockTaskEnqueuerMockRecorder is the mock recorder for MockTaskEnqueuer.
type MockTaskEnqueuerMockRecorder struct {
	mock *MockTaskEnqueuer
}

// NewMockTaskEnqueuer creates a new mock instance.
func NewMockTaskEnqueuer(ctrl *gomock.Controller) *MockTaskEnqueuer {
	mock := &MockTaskEnqueuer{ctrl: ctrl}
	mock.recorder = &MockTaskEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskEnqueuer) EXPECT() *MockTaskEnqueuerMockRecorder {
	return m.recorder
}

// EnqueueTransactionWithPriority mocks base method.
func (m *MockTaskEnqueuer) EnqueueTransactionWithPriority(ctx context.Context, event models.Event, priority string) (*asynq.TaskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTransactionWithPriority", ctx, event, priority)
	ret0, _ := ret[0].(*asynq.TaskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueTransactionWithPriority indicates an expected call of EnqueueTransactionWithPriority.
func (mr *MockTaskEnqueuerMockRecorder) EnqueueTransactionWithPriority(ctx, event, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTransactionWithPriority", reflect.TypeOf((*MockTaskEnqueuer)(nil).EnqueueTransactionWithPriority), ctx, event, priority)
}
