// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/branding/service.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/branding/service.go -destination=src/api/internal/branding/mock_service_test.go -package=branding
//

// Package branding is a generated GoMock package.
package branding

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBranding mocks base method.
func (m *MockService) GetBranding(ctx context.Context) (*models.BrandingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranding", ctx)
	ret0, _ := ret[0].(*models.BrandingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranding indicates an expected call of GetBranding.
func (mr *MockServiceMockRecorder) GetBranding(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranding", reflect.TypeOf((*MockService)(nil).GetBranding), ctx)
}

// UpdateBranding mocks base method.
func (m *MockService) UpdateBranding(ctx context.Context, req *UpdateBrandingRequest) (*models.BrandingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranding", ctx, req)
	ret0, _ := ret[0].(*models.BrandingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBranding indicates an expected call of UpdateBranding.
func (mr *MockServiceMockRecorder) UpdateBranding(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranding", reflect.TypeOf((*MockService)(nil).UpdateBranding), ctx, req)
}
