// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/groups/repository.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/groups/repository.go -destination=src/api/internal/groups/mock_repository_test.go -package=groups
//

// Package groups is a generated GoMock package.
package groups

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetGroupByID mocks base method.
func (m *MockRepository) GetGroupByID(ctx context.Context, groupID uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, groupID)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockRepositoryMockRecorder) GetGroupByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockRepository)(nil).GetGroupByID), ctx, groupID)
}

// GetGroupByName mocks base method.
func (m *MockRepository) GetGroupByName(ctx context.Context, name string) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", ctx, name)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockRepositoryMockRecorder) GetGroupByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockRepository)(nil).GetGroupByName), ctx, name)
}

// ListGroups mocks base method.
func (m *MockRepository) ListGroups(ctx context.Context) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockRepositoryMockRecorder) ListGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockRepository)(nil).ListGroups), ctx)
}

// LoadGroupRoles mocks base method.
func (m *MockRepository) LoadGroupRoles(ctx context.Context, groupID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGroupRoles", ctx, groupID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGroupRoles indicates an expected call of LoadGroupRoles.
func (mr *MockRepositoryMockRecorder) LoadGroupRoles(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGroupRoles", reflect.TypeOf((*MockRepository)(nil).LoadGroupRoles), ctx, groupID)
}

// LoadUserGroups mocks base method.
func (m *MockRepository) LoadUserGroups(ctx context.Context, userID uuid.UUID) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserGroups", ctx, userID)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserGroups indicates an expected call of LoadUserGroups.
func (mr *MockRepositoryMockRecorder) LoadUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserGroups", reflect.TypeOf((*MockRepository)(nil).LoadUserGroups), ctx, userID)
}
