// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/groups/service.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/groups/service.go -destination=src/api/internal/groups/mock_service_test.go -package=groups Service
//

// Package groups is a generated GoMock package.
package groups

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetGroupByID mocks base method.
func (m *MockService) GetGroupByID(ctx context.Context, groupID uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, groupID)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockServiceMockRecorder) GetGroupByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockService)(nil).GetGroupByID), ctx, groupID)
}

// GetGroupByName mocks base method.
func (m *MockService) GetGroupByName(ctx context.Context, name string) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", ctx, name)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockServiceMockRecorder) GetGroupByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockService)(nil).GetGroupByName), ctx, name)
}

// ListGroups mocks base method.
func (m *MockService) ListGroups(ctx context.Context) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockServiceMockRecorder) ListGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockService)(nil).ListGroups), ctx)
}

// LoadGroupRoles mocks base method.
func (m *MockService) LoadGroupRoles(ctx context.Context, groupID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGroupRoles", ctx, groupID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGroupRoles indicates an expected call of LoadGroupRoles.
func (mr *MockServiceMockRecorder) LoadGroupRoles(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGroupRoles", reflect.TypeOf((*MockService)(nil).LoadGroupRoles), ctx, groupID)
}

// LoadUserGroups mocks base method.
func (m *MockService) LoadUserGroups(ctx context.Context, userID uuid.UUID) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserGroups", ctx, userID)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserGroups indicates an expected call of LoadUserGroups.
func (mr *MockServiceMockRecorder) LoadUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserGroups", reflect.TypeOf((*MockService)(nil).LoadUserGroups), ctx, userID)
}
