// Code generated by MockGen. DO NOT EDIT.
// Source: service interfaces (manually created for testing)

package user

import (
	context "context"
	reflect "reflect"

	groups "github.com/algo-shield/algo-shield/src/api/internal/groups"
	roles "github.com/algo-shield/algo-shield/src/api/internal/roles"
	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleService is a mock of roles.Service interface.
type MockRoleService struct {
	ctrl     *gomock.Controller
	recorder *MockRoleServiceMockRecorder
}

// MockRoleServiceMockRecorder is the mock recorder for MockRoleService.
type MockRoleServiceMockRecorder struct {
	mock *MockRoleService
}

// NewMockRoleService creates a new mock instance.
func NewMockRoleService(ctrl *gomock.Controller) *MockRoleService {
	mock := &MockRoleService{ctrl: ctrl}
	mock.recorder = &MockRoleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleService) EXPECT() *MockRoleServiceMockRecorder {
	return m.recorder
}

// ListRoles mocks base method.
func (m *MockRoleService) ListRoles(ctx context.Context) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleServiceMockRecorder) ListRoles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleService)(nil).ListRoles), ctx)
}

// GetRoleByID mocks base method.
func (m *MockRoleService) GetRoleByID(ctx context.Context, id uuid.UUID) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRoleServiceMockRecorder) GetRoleByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRoleService)(nil).GetRoleByID), ctx, id)
}

// GetRoleByName mocks base method.
func (m *MockRoleService) GetRoleByName(ctx context.Context, name string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockRoleServiceMockRecorder) GetRoleByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockRoleService)(nil).GetRoleByName), ctx, name)
}

// AssignRole mocks base method.
func (m *MockRoleService) AssignRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleServiceMockRecorder) AssignRole(ctx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleService)(nil).AssignRole), ctx, userID, roleID)
}

// RemoveRole mocks base method.
func (m *MockRoleService) RemoveRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRoleServiceMockRecorder) RemoveRole(ctx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRoleService)(nil).RemoveRole), ctx, userID, roleID)
}

// LoadUserRoles mocks base method.
func (m *MockRoleService) LoadUserRoles(ctx context.Context, userID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserRoles", ctx, userID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserRoles indicates an expected call of LoadUserRoles.
func (mr *MockRoleServiceMockRecorder) LoadUserRoles(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserRoles", reflect.TypeOf((*MockRoleService)(nil).LoadUserRoles), ctx, userID)
}

// Ensure MockRoleService implements roles.Service
var _ roles.Service = (*MockRoleService)(nil)

// MockGroupService is a mock of groups.Service interface.
type MockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceMockRecorder
}

// MockGroupServiceMockRecorder is the mock recorder for MockGroupService.
type MockGroupServiceMockRecorder struct {
	mock *MockGroupService
}

// NewMockGroupService creates a new mock instance.
func NewMockGroupService(ctrl *gomock.Controller) *MockGroupService {
	mock := &MockGroupService{ctrl: ctrl}
	mock.recorder = &MockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupService) EXPECT() *MockGroupServiceMockRecorder {
	return m.recorder
}

// ListGroups mocks base method.
func (m *MockGroupService) ListGroups(ctx context.Context) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupServiceMockRecorder) ListGroups(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupService)(nil).ListGroups), ctx)
}

// GetGroupByID mocks base method.
func (m *MockGroupService) GetGroupByID(ctx context.Context, id uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupServiceMockRecorder) GetGroupByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupService)(nil).GetGroupByID), ctx, id)
}

// GetGroupByName mocks base method.
func (m *MockGroupService) GetGroupByName(ctx context.Context, name string) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", ctx, name)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockGroupServiceMockRecorder) GetGroupByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockGroupService)(nil).GetGroupByName), ctx, name)
}

// LoadUserGroups mocks base method.
func (m *MockGroupService) LoadUserGroups(ctx context.Context, userID uuid.UUID) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserGroups", ctx, userID)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserGroups indicates an expected call of LoadUserGroups.
func (mr *MockGroupServiceMockRecorder) LoadUserGroups(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserGroups", reflect.TypeOf((*MockGroupService)(nil).LoadUserGroups), ctx, userID)
}

// LoadGroupRoles mocks base method.
func (m *MockGroupService) LoadGroupRoles(ctx context.Context, groupID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGroupRoles", ctx, groupID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGroupRoles indicates an expected call of LoadGroupRoles.
func (mr *MockGroupServiceMockRecorder) LoadGroupRoles(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGroupRoles", reflect.TypeOf((*MockGroupService)(nil).LoadGroupRoles), ctx, groupID)
}

// Ensure MockGroupService implements groups.Service
var _ groups.Service = (*MockGroupService)(nil)

// MockRoleRepository is a mock of roles.Repository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// GetRoleIDByName mocks base method.
func (m *MockRoleRepository) GetRoleIDByName(ctx context.Context, tx pgx.Tx, name string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleIDByName", ctx, tx, name)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleIDByName indicates an expected call of GetRoleIDByName.
func (mr *MockRoleRepositoryMockRecorder) GetRoleIDByName(ctx, tx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleIDByName", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleIDByName), ctx, tx, name)
}

// AssignRoleToUser mocks base method.
func (m *MockRoleRepository) AssignRoleToUser(ctx context.Context, tx pgx.Tx, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, tx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockRoleRepositoryMockRecorder) AssignRoleToUser(ctx, tx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockRoleRepository)(nil).AssignRoleToUser), ctx, tx, userID, roleID)
}

// ListRoles mocks base method.
func (m *MockRoleRepository) ListRoles(ctx context.Context) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleRepositoryMockRecorder) ListRoles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListRoles), ctx)
}

// GetRoleByID mocks base method.
func (m *MockRoleRepository) GetRoleByID(ctx context.Context, id uuid.UUID) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRoleRepositoryMockRecorder) GetRoleByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleByID), ctx, id)
}

// GetRoleByName mocks base method.
func (m *MockRoleRepository) GetRoleByName(ctx context.Context, name string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockRoleRepositoryMockRecorder) GetRoleByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleByName), ctx, name)
}

// AssignRole mocks base method.
func (m *MockRoleRepository) AssignRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleRepositoryMockRecorder) AssignRole(ctx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleRepository)(nil).AssignRole), ctx, userID, roleID)
}

// RemoveRole mocks base method.
func (m *MockRoleRepository) RemoveRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRoleRepositoryMockRecorder) RemoveRole(ctx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRoleRepository)(nil).RemoveRole), ctx, userID, roleID)
}

// LoadUserRoles mocks base method.
func (m *MockRoleRepository) LoadUserRoles(ctx context.Context, userID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserRoles", ctx, userID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserRoles indicates an expected call of LoadUserRoles.
func (mr *MockRoleRepositoryMockRecorder) LoadUserRoles(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserRoles", reflect.TypeOf((*MockRoleRepository)(nil).LoadUserRoles), ctx, userID)
}

// Ensure MockRoleRepository implements roles.Repository
var _ roles.Repository = (*MockRoleRepository)(nil)
