// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dashboard/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/dashboard/repository.go -destination=internal/dashboard/mock_repository.go -package=dashboard Repository
//

// Package dashboard is a generated GoMock package.
package dashboard

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetStatusDistribution mocks base method.
func (m *MockRepository) GetStatusDistribution(ctx context.Context) ([]StatusCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusDistribution", ctx)
	ret0, _ := ret[0].([]StatusCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusDistribution indicates an expected call of GetStatusDistribution.
func (mr *MockRepositoryMockRecorder) GetStatusDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusDistribution", reflect.TypeOf((*MockRepository)(nil).GetStatusDistribution), ctx)
}

// GetTemporalCounts mocks base method.
func (m *MockRepository) GetTemporalCounts(ctx context.Context, period string) ([]TemporalCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemporalCounts", ctx, period)
	ret0, _ := ret[0].([]TemporalCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemporalCounts indicates an expected call of GetTemporalCounts.
func (mr *MockRepositoryMockRecorder) GetTemporalCounts(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemporalCounts", reflect.TypeOf((*MockRepository)(nil).GetTemporalCounts), ctx, period)
}

// GetTotalCount mocks base method.
func (m *MockRepository) GetTotalCount(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalCount", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalCount indicates an expected call of GetTotalCount.
func (mr *MockRepositoryMockRecorder) GetTotalCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalCount", reflect.TypeOf((*MockRepository)(nil).GetTotalCount), ctx)
}
