// Code generated by MockGen. DO NOT EDIT.
// Source: src/pkg/rules/repository.go
//
// Generated by this command:
//
//	mockgen -source=src/pkg/rules/repository.go -destination=src/api/internal/rules/mock_repository_test.go -package=rules
//

// Package rules is a generated GoMock package.
package rules

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleReader is a mock of RuleReader interface.
type MockRuleReader struct {
	ctrl     *gomock.Controller
	recorder *MockRuleReaderMockRecorder
	isgomock struct{}
}

// MockRuleReaderMockRecorder is the mock recorder for MockRuleReader.
type MockRuleReaderMockRecorder struct {
	mock *MockRuleReader
}

// NewMockRuleReader creates a new mock instance.
func NewMockRuleReader(ctrl *gomock.Controller) *MockRuleReader {
	mock := &MockRuleReader{ctrl: ctrl}
	mock.recorder = &MockRuleReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleReader) EXPECT() *MockRuleReaderMockRecorder {
	return m.recorder
}

// LoadRules mocks base method.
func (m *MockRuleReader) LoadRules(ctx context.Context) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRules", ctx)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRules indicates an expected call of LoadRules.
func (mr *MockRuleReaderMockRecorder) LoadRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRules", reflect.TypeOf((*MockRuleReader)(nil).LoadRules), ctx)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRule mocks base method.
func (m *MockRepository) CreateRule(ctx context.Context, rule *models.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockRepositoryMockRecorder) CreateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockRepository)(nil).CreateRule), ctx, rule)
}

// DeleteRule mocks base method.
func (m *MockRepository) DeleteRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockRepositoryMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockRepository)(nil).DeleteRule), ctx, id)
}

// GetRule mocks base method.
func (m *MockRepository) GetRule(ctx context.Context, id uuid.UUID) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockRepositoryMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockRepository)(nil).GetRule), ctx, id)
}

// ListRules mocks base method.
func (m *MockRepository) ListRules(ctx context.Context) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockRepositoryMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockRepository)(nil).ListRules), ctx)
}

// LoadRules mocks base method.
func (m *MockRepository) LoadRules(ctx context.Context) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRules", ctx)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRules indicates an expected call of LoadRules.
func (mr *MockRepositoryMockRecorder) LoadRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRules", reflect.TypeOf((*MockRepository)(nil).LoadRules), ctx)
}

// UpdateRule mocks base method.
func (m *MockRepository) UpdateRule(ctx context.Context, rule *models.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockRepositoryMockRecorder) UpdateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockRepository)(nil).UpdateRule), ctx, rule)
}
