// Code generated by MockGen. DO NOT EDIT.
// Source: src/api/internal/health/handler.go
//
// Generated by this command:
//
//	mockgen -source=src/api/internal/health/handler.go -destination=src/api/internal/health/mock_health_test.go -package=health
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	reflect "reflect"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseHealthChecker is a mock of DatabaseHealthChecker interface.
type MockDatabaseHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseHealthCheckerMockRecorder
	isgomock struct{}
}

// MockDatabaseHealthCheckerMockRecorder is the mock recorder for MockDatabaseHealthChecker.
type MockDatabaseHealthCheckerMockRecorder struct {
	mock *MockDatabaseHealthChecker
}

// NewMockDatabaseHealthChecker creates a new mock instance.
func NewMockDatabaseHealthChecker(ctrl *gomock.Controller) *MockDatabaseHealthChecker {
	mock := &MockDatabaseHealthChecker{ctrl: ctrl}
	mock.recorder = &MockDatabaseHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseHealthChecker) EXPECT() *MockDatabaseHealthCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDatabaseHealthChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseHealthCheckerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabaseHealthChecker)(nil).Ping), ctx)
}

// MockRedisHealthChecker is a mock of RedisHealthChecker interface.
type MockRedisHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRedisHealthCheckerMockRecorder
	isgomock struct{}
}

// MockRedisHealthCheckerMockRecorder is the mock recorder for MockRedisHealthChecker.
type MockRedisHealthCheckerMockRecorder struct {
	mock *MockRedisHealthChecker
}

// NewMockRedisHealthChecker creates a new mock instance.
func NewMockRedisHealthChecker(ctrl *gomock.Controller) *MockRedisHealthChecker {
	mock := &MockRedisHealthChecker{ctrl: ctrl}
	mock.recorder = &MockRedisHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisHealthChecker) EXPECT() *MockRedisHealthCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockRedisHealthChecker) Ping(ctx context.Context) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisHealthCheckerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisHealthChecker)(nil).Ping), ctx)
}
