// Code generated by MockGen. DO NOT EDIT.
// Source: ../groups/service.go
//
// Generated by this command:
//
//	mockgen -source=../groups/service.go -destination=mock_group_service_test.go -package=permissions -mock_names=Service=MockGroupService
//

// Package permissions is a generated GoMock package.
package permissions

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupService is a mock of Service interface.
type MockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceMockRecorder
	isgomock struct{}
}

// MockGroupServiceMockRecorder is the mock recorder for MockGroupService.
type MockGroupServiceMockRecorder struct {
	mock *MockGroupService
}

// NewMockGroupService creates a new mock instance.
func NewMockGroupService(ctrl *gomock.Controller) *MockGroupService {
	mock := &MockGroupService{ctrl: ctrl}
	mock.recorder = &MockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupService) EXPECT() *MockGroupServiceMockRecorder {
	return m.recorder
}

// GetGroupByID mocks base method.
func (m *MockGroupService) GetGroupByID(ctx context.Context, groupID uuid.UUID) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, groupID)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupServiceMockRecorder) GetGroupByID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupService)(nil).GetGroupByID), ctx, groupID)
}

// GetGroupByName mocks base method.
func (m *MockGroupService) GetGroupByName(ctx context.Context, name string) (*models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", ctx, name)
	ret0, _ := ret[0].(*models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockGroupServiceMockRecorder) GetGroupByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockGroupService)(nil).GetGroupByName), ctx, name)
}

// ListGroups mocks base method.
func (m *MockGroupService) ListGroups(ctx context.Context) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupServiceMockRecorder) ListGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupService)(nil).ListGroups), ctx)
}

// LoadGroupRoles mocks base method.
func (m *MockGroupService) LoadGroupRoles(ctx context.Context, groupID uuid.UUID) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGroupRoles", ctx, groupID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGroupRoles indicates an expected call of LoadGroupRoles.
func (mr *MockGroupServiceMockRecorder) LoadGroupRoles(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGroupRoles", reflect.TypeOf((*MockGroupService)(nil).LoadGroupRoles), ctx, groupID)
}

// LoadUserGroups mocks base method.
func (m *MockGroupService) LoadUserGroups(ctx context.Context, userID uuid.UUID) ([]models.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUserGroups", ctx, userID)
	ret0, _ := ret[0].([]models.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUserGroups indicates an expected call of LoadUserGroups.
func (mr *MockGroupServiceMockRecorder) LoadUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUserGroups", reflect.TypeOf((*MockGroupService)(nil).LoadUserGroups), ctx, userID)
}
