// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_permissionsservice_test.go -package=permissions -mock_names=PermissionsService=MockPermissionsService PermissionsService
//

// Package permissions is a generated GoMock package.
package permissions

import (
	context "context"
	reflect "reflect"

	models "github.com/algo-shield/algo-shield/src/pkg/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionsService is a mock of PermissionsService interface.
type MockPermissionsService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionsServiceMockRecorder
	isgomock struct{}
}

// MockPermissionsServiceMockRecorder is the mock recorder for MockPermissionsService.
type MockPermissionsServiceMockRecorder struct {
	mock *MockPermissionsService
}

// NewMockPermissionsService creates a new mock instance.
func NewMockPermissionsService(ctrl *gomock.Controller) *MockPermissionsService {
	mock := &MockPermissionsService{ctrl: ctrl}
	mock.recorder = &MockPermissionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionsService) EXPECT() *MockPermissionsServiceMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockPermissionsService) GetUserByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockPermissionsServiceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockPermissionsService)(nil).GetUserByID), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockPermissionsService) ListUsers(ctx context.Context) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockPermissionsServiceMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockPermissionsService)(nil).ListUsers), ctx)
}

// UpdateUserActive mocks base method.
func (m *MockPermissionsService) UpdateUserActive(ctx context.Context, currentUserID, targetUserID uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserActive", ctx, currentUserID, targetUserID, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserActive indicates an expected call of UpdateUserActive.
func (mr *MockPermissionsServiceMockRecorder) UpdateUserActive(ctx, currentUserID, targetUserID, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserActive", reflect.TypeOf((*MockPermissionsService)(nil).UpdateUserActive), ctx, currentUserID, targetUserID, active)
}
