package schemas

// RealisticNames contains 1000 realistic full names for synthetic data generation
// Names are a mix of common names from various cultures and regions
var RealisticNames = []string{
	// American/English names
	"James Anderson", "Michael Johnson", "Robert Williams", "David Brown", "William Jones",
	"Richard Garcia", "Joseph Miller", "Thomas Davis", "Charles Rodriguez", "Christopher Martinez",
	"Daniel Hernandez", "Matthew Lopez", "Anthony Gonzalez", "Mark Wilson", "Donald Moore",
	"Steven Taylor", "Paul Thomas", "Andrew Jackson", "Joshua White", "Kenneth Harris",
	"Kevin Martin", "Brian Thompson", "George Clark", "Timothy Lewis", "Ronald Robinson",
	"Edward Walker", "Jason Hall", "Jeffrey Allen", "Ryan Young", "Jacob King",
	"Mary Smith", "Patricia Johnson", "Jennifer Williams", "Linda Brown", "Barbara Jones",
	"Elizabeth Garcia", "Susan Miller", "Jessica Davis", "Sarah Rodriguez", "Karen Martinez",
	"Lisa Hernandez", "Nancy Lopez", "Betty Gonzalez", "Margaret Wilson", "Sandra Moore",
	"Ashley Taylor", "Kimberly Thomas", "Emily Jackson", "Donna White", "Michelle Harris",
	"Dorothy Martin", "Carol Thompson", "Amanda Clark", "Melissa Lewis", "Deborah Robinson",
	"Stephanie Walker", "Rebecca Hall", "Sharon Allen", "Laura Young", "Cynthia King",
	// Brazilian/Portuguese names
	"João Silva", "Pedro Santos", "Carlos Oliveira", "Paulo Souza", "Lucas Pereira",
	"Marcos Costa", "José Ferreira", "Antonio Rodrigues", "Rafael Almeida", "Bruno Lima",
	"Gabriel Gomes", "Felipe Ribeiro", "Rodrigo Martins", "Leonardo Carvalho", "Eduardo Araújo",
	"Gustavo Melo", "Fernando Barbosa", "Thiago Cardoso", "Matheus Nascimento", "Marcelo Rocha",
	"Maria Silva", "Ana Santos", "Juliana Oliveira", "Camila Souza", "Fernanda Pereira",
	"Patrícia Costa", "Amanda Ferreira", "Luciana Rodrigues", "Bruna Almeida", "Mariana Lima",
	"Carolina Gomes", "Beatriz Ribeiro", "Larissa Martins", "Isabela Carvalho", "Letícia Araújo",
	"Raquel Melo", "Vanessa Barbosa", "Natália Cardoso", "Renata Nascimento", "Priscila Rocha",
	// Spanish names
	"Miguel Hernández", "Carlos García", "José López", "Juan Martínez", "Luis Rodríguez",
	"Francisco González", "Antonio Pérez", "Manuel Sánchez", "Pedro Ramírez", "Javier Torres",
	"Alejandro Flores", "Diego Ruiz", "Sergio Morales", "Pablo Jiménez", "Roberto Vargas",
	"Fernando Reyes", "Ricardo Cruz", "Alberto Díaz", "Andrés Moreno", "Raúl Ortiz",
	"María García", "Carmen López", "Ana Martínez", "Laura Rodríguez", "Isabel González",
	"Rosa Pérez", "Lucia Sánchez", "Elena Ramírez", "Marta Torres", "Cristina Flores",
	"Patricia Ruiz", "Paula Morales", "Andrea Jiménez", "Sara Vargas", "Beatriz Reyes",
	"Claudia Cruz", "Silvia Díaz", "Mónica Moreno", "Alicia Ortiz", "Pilar Méndez",
	// German names
	"Thomas Müller", "Michael Schmidt", "Wolfgang Fischer", "Andreas Weber", "Peter Meyer",
	"Klaus Wagner", "Stefan Becker", "Hans Hoffmann", "Martin Schulz", "Christian Koch",
	"Markus Richter", "Frank Klein", "Jürgen Wolf", "Uwe Schröder", "Bernd Neumann",
	"Ralf Schwarz", "Dieter Braun", "Helmut Zimmermann", "Joachim Krüger", "Werner Lange",
	"Anna Müller", "Maria Schmidt", "Ursula Fischer", "Monika Weber", "Elisabeth Meyer",
	"Helga Wagner", "Karin Becker", "Ingrid Hoffmann", "Gisela Schulz", "Renate Koch",
	"Sabine Richter", "Petra Klein", "Brigitte Wolf", "Erika Schröder", "Gertrud Neumann",
	"Andrea Schwarz", "Claudia Braun", "Heike Zimmermann", "Birgit Krüger", "Martina Lange",
	// French names
	"Jean Dupont", "Pierre Martin", "Michel Bernard", "François Dubois", "Jacques Thomas",
	"Philippe Robert", "André Richard", "Louis Petit", "Claude Durand", "Paul Leroy",
	"Henri Moreau", "Alain Simon", "Laurent Michel", "Patrick Lefebvre", "Gérard Lecomte",
	"Christophe Garcia", "Nicolas David", "Thierry Bertrand", "Olivier Roux", "Marc Vincent",
	"Marie Dupont", "Françoise Martin", "Monique Bernard", "Nicole Dubois", "Sylvie Thomas",
	"Nathalie Robert", "Catherine Richard", "Isabelle Petit", "Valérie Durand", "Sandrine Leroy",
	"Christine Moreau", "Céline Simon", "Anne Michel", "Véronique Lefebvre", "Martine Lecomte",
	"Caroline Garcia", "Sophie David", "Julie Bertrand", "Émilie Roux", "Stéphanie Vincent",
	// Italian names
	"Marco Rossi", "Giuseppe Russo", "Alessandro Ferrari", "Francesco Esposito", "Lorenzo Bianchi",
	"Andrea Romano", "Luca Colombo", "Giovanni Ricci", "Paolo Marino", "Stefano Greco",
	"Matteo Bruno", "Antonio Gallo", "Davide Conti", "Roberto Costa", "Fabio De Luca",
	"Simone Giordano", "Alberto Mancini", "Claudio Rizzo", "Massimo Lombardi", "Daniele Moretti",
	"Maria Rossi", "Giuseppina Russo", "Lucia Ferrari", "Rosa Esposito", "Francesca Bianchi",
	"Angela Romano", "Giovanna Colombo", "Anna Ricci", "Paola Marino", "Carla Greco",
	"Elena Bruno", "Antonietta Gallo", "Rita Conti", "Teresa Costa", "Silvia De Luca",
	"Laura Giordano", "Sara Mancini", "Valentina Rizzo", "Chiara Lombardi", "Elisa Moretti",
	// Japanese names (romanized)
	"Takeshi Tanaka", "Hiroshi Yamamoto", "Kenji Watanabe", "Yuki Suzuki", "Taro Sato",
	"Akira Nakamura", "Masashi Kobayashi", "Kazuki Kato", "Ryota Yoshida", "Shota Yamada",
	"Daiki Sasaki", "Naoki Yamaguchi", "Yuto Matsumoto", "Kenta Inoue", "Sota Kimura",
	"Hayato Hayashi", "Riku Shimizu", "Haruki Yamazaki", "Kaito Mori", "Ren Ikeda",
	"Yuko Tanaka", "Keiko Yamamoto", "Akiko Watanabe", "Sachiko Suzuki", "Michiko Sato",
	"Haruko Nakamura", "Tomoko Kobayashi", "Yuki Kato", "Megumi Yoshida", "Naomi Yamada",
	"Mika Sasaki", "Emi Yamaguchi", "Ai Matsumoto", "Rina Inoue", "Yui Kimura",
	"Sakura Hayashi", "Nana Shimizu", "Hana Yamazaki", "Aoi Mori", "Mei Ikeda",
	// Chinese names (romanized)
	"Wei Zhang", "Jian Wang", "Ming Li", "Qiang Liu", "Wei Chen",
	"Lei Yang", "Tao Huang", "Jun Zhao", "Yong Wu", "Chao Zhou",
	"Hao Xu", "Peng Sun", "Bo Ma", "Feng Zhu", "Jie Hu",
	"Gang Lin", "Xin Guo", "Yu He", "Kai Luo", "Long Liang",
	"Li Zhang", "Xiu Wang", "Fang Li", "Juan Liu", "Ying Chen",
	"Mei Yang", "Hong Huang", "Lan Zhao", "Ping Wu", "Na Zhou",
	"Yan Xu", "Hui Sun", "Jing Ma", "Wen Zhu", "Qing Hu",
	"Ling Lin", "Rong Guo", "Min He", "Xia Luo", "Chun Liang",
	// Korean names (romanized)
	"Min-jun Kim", "Seo-jun Lee", "Do-yun Park", "Ye-jun Choi", "Ju-won Jung",
	"Jae-won Kang", "Jun-seo Yoon", "Hyun-woo Jo", "Ji-hoon Jang", "Seong-min Han",
	"Dong-hyun Im", "Yun-ho Song", "Sung-ho Yang", "Jin-woo Ahn", "Tae-yong Kwon",
	"Joon-hyuk Oh", "Hye-sung Seo", "Sang-woo Shin", "Dae-ho Hwang", "Woo-jin Hong",
	"Soo-yeon Kim", "Min-ji Lee", "Ji-young Park", "Eun-ji Choi", "Hye-jin Jung",
	"Seo-yun Kang", "Su-bin Yoon", "Ji-won Jo", "Yu-jin Jang", "Hae-won Han",
	"Yun-seo Im", "Eun-seo Song", "Yoo-na Yang", "Ha-na Ahn", "Ji-eun Kwon",
	"Soo-min Oh", "Min-seo Seo", "Ye-eun Shin", "Seo-hyun Hwang", "Hyun-ji Hong",
	// Indian names
	"Rajesh Kumar", "Suresh Sharma", "Ramesh Patel", "Amit Singh", "Sanjay Gupta",
	"Vikram Verma", "Arun Joshi", "Deepak Agarwal", "Ravi Mehta", "Manoj Kapoor",
	"Vijay Rao", "Sunil Saxena", "Anand Malhotra", "Ashish Chopra", "Pradeep Khanna",
	"Rahul Bhatia", "Nitin Mishra", "Ajay Trivedi", "Sandeep Pandey", "Gaurav Srivastava",
	"Priya Sharma", "Anita Patel", "Sunita Singh", "Neha Gupta", "Pooja Verma",
	"Kavita Joshi", "Meena Agarwal", "Rekha Mehta", "Sarita Kapoor", "Archana Rao",
	"Divya Saxena", "Swati Malhotra", "Seema Chopra", "Anjali Khanna", "Pallavi Bhatia",
	"Shweta Mishra", "Manisha Trivedi", "Nisha Pandey", "Ritu Srivastava", "Deepika Das",
	// Russian names
	"Ivan Petrov", "Dmitri Ivanov", "Sergei Smirnov", "Alexei Kuznetsov", "Mikhail Popov",
	"Vladimir Sokolov", "Andrei Lebedev", "Nikolai Kozlov", "Pavel Novikov", "Yuri Morozov",
	"Viktor Volkov", "Oleg Fedorov", "Igor Mikhailov", "Vasili Alekseev", "Boris Sorokin",
	"Roman Baranov", "Grigori Pavlov", "Anatoli Orlov", "Evgeni Kiselev", "Konstantin Zaitsev",
	"Anna Petrova", "Maria Ivanova", "Elena Smirnova", "Olga Kuznetsova", "Natalia Popova",
	"Tatiana Sokolova", "Ekaterina Lebedeva", "Yulia Kozlova", "Irina Novikova", "Svetlana Morozova",
	"Valentina Volkova", "Galina Fedorova", "Nina Mikhailova", "Lyudmila Alekseeva", "Vera Sorokina",
	"Larisa Baranova", "Oksana Pavlova", "Marina Orlova", "Tamara Kiseleva", "Nadezhda Zaitseva",
	// Arabic names
	"Ahmed Hassan", "Mohamed Ali", "Mahmoud Ibrahim", "Omar Abdullah", "Youssef Mustafa",
	"Khalid Salem", "Ali Hussein", "Hassan Ahmad", "Tariq Mohammed", "Kareem Farouq",
	"Nabil Samir", "Fadi Rashid", "Samir Jamil", "Rami Saleh", "Walid Nasser",
	"Hisham Karim", "Bassam Jamal", "Ziad Adel", "Amir Tarek", "Bilal Hakim",
	"Fatima Hassan", "Aisha Ali", "Mariam Ibrahim", "Sara Abdullah", "Nour Mustafa",
	"Layla Salem", "Hana Hussein", "Yasmin Ahmad", "Rania Mohammed", "Dina Farouq",
	"Amira Samir", "Lina Rashid", "Mona Jamil", "Rana Saleh", "Sana Nasser",
	"Hiba Karim", "Nadine Jamal", "Reem Adel", "Nadia Tarek", "Salma Hakim",
	// African names
	"Kwame Asante", "Kofi Mensah", "Yaw Owusu", "Kwesi Boateng", "Nana Adjei",
	"Chidi Okonkwo", "Emeka Eze", "Tunde Adeyemi", "Olumide Babatunde", "Segun Afolabi",
	"Sipho Nkosi", "Thabo Dlamini", "Bongani Ndlovu", "Mandla Zulu", "Themba Mkhize",
	"Abdul Diallo", "Moussa Traore", "Mamadou Diop", "Ibrahim Camara", "Oumar Sy",
	"Amara Asante", "Akua Mensah", "Abena Owusu", "Efua Boateng", "Adwoa Adjei",
	"Ngozi Okonkwo", "Chioma Eze", "Funke Adeyemi", "Yetunde Babatunde", "Bisi Afolabi",
	"Nomvula Nkosi", "Thandi Dlamini", "Lindiwe Ndlovu", "Nonhlanhla Zulu", "Zanele Mkhize",
	"Aminata Diallo", "Fatoumata Traore", "Awa Diop", "Mariama Camara", "Oumou Sy",
	// Turkish names
	"Mehmet Yılmaz", "Mustafa Kaya", "Ahmet Demir", "Ali Çelik", "Hasan Şahin",
	"Hüseyin Yıldız", "İbrahim Öztürk", "Murat Aydın", "Osman Özdemir", "Fatih Arslan",
	"Emre Doğan", "Can Kılıç", "Burak Aslan", "Serkan Koç", "Cem Korkmaz",
	"Erhan Yılmaz", "Tolga Kurt", "Özgür Özkan", "Selim Şimşek", "Umut Çetin",
	"Ayşe Yılmaz", "Fatma Kaya", "Emine Demir", "Hatice Çelik", "Zeynep Şahin",
	"Elif Yıldız", "Merve Öztürk", "Esra Aydın", "Büşra Özdemir", "Seda Arslan",
	"Gizem Doğan", "Nur Kılıç", "Beren Aslan", "Deniz Koç", "Ece Korkmaz",
	"İrem Yılmaz", "Beyza Kurt", "Cansu Özkan", "Pınar Şimşek", "Sinem Çetin",
	// Polish names
	"Jan Kowalski", "Piotr Nowak", "Tomasz Wiśniewski", "Andrzej Wójcik", "Krzysztof Kowalczyk",
	"Stanisław Kamiński", "Jerzy Lewandowski", "Zbigniew Zieliński", "Marek Szymański", "Adam Woźniak",
	"Michał Dąbrowski", "Paweł Kozłowski", "Rafał Jankowski", "Marcin Wojciechowski", "Jakub Kwiatkowski",
	"Łukasz Kaczmarek", "Wojciech Piotrowski", "Maciej Grabowski", "Mateusz Pawłowski", "Kamil Michalski",
	"Anna Kowalska", "Maria Nowak", "Katarzyna Wiśniewska", "Małgorzata Wójcik", "Agnieszka Kowalczyk",
	"Barbara Kamińska", "Ewa Lewandowska", "Krystyna Zielińska", "Elżbieta Szymańska", "Zofia Woźniak",
	"Magdalena Dąbrowska", "Joanna Kozłowska", "Monika Jankowska", "Aleksandra Wojciechowska", "Natalia Kwiatkowska",
	"Karolina Kaczmarek", "Justyna Piotrowska", "Patrycja Grabowska", "Dominika Pawłowska", "Paulina Michalska",
	// Dutch names
	"Jan de Vries", "Pieter Bakker", "Johannes Visser", "Cornelis Smit", "Willem Meijer",
	"Hendrik Mulder", "Gerrit de Boer", "Jacobus Dekker", "Petrus Dijkstra", "Dirk van den Berg",
	"Marinus Bos", "Adrianus Jansen", "Theodorus Peters", "Franciscus van Dijk", "Bernardus Hendriks",
	"Antonius de Jong", "Lambertus Kramer", "Martinus van Leeuwen", "Nicolaas Brouwer", "Albertus Huisman",
	"Maria de Vries", "Johanna Bakker", "Anna Visser", "Elisabeth Smit", "Hendrika Meijer",
	"Cornelia Mulder", "Petronella de Boer", "Wilhelmina Dekker", "Geertruida Dijkstra", "Adriana van den Berg",
	"Jacoba Bos", "Margaretha Jansen", "Christina Peters", "Antonia van Dijk", "Helena Hendriks",
	"Catharina de Jong", "Theodora Kramer", "Francisca van Leeuwen", "Johanna Brouwer", "Maria Huisman",
	// Swedish names
	"Erik Andersson", "Lars Johansson", "Karl Karlsson", "Anders Nilsson", "Johan Eriksson",
	"Per Larsson", "Nils Olsson", "Sven Persson", "Gustav Svensson", "Olof Gustafsson",
	"Magnus Pettersson", "Fredrik Jonsson", "Henrik Jansson", "Stefan Hansson", "Peter Bengtsson",
	"Mikael Lindqvist", "Hans Lindgren", "Thomas Axelsson", "Daniel Berglund", "Martin Bergström",
	"Maria Andersson", "Anna Johansson", "Margareta Karlsson", "Elisabeth Nilsson", "Eva Eriksson",
	"Kristina Larsson", "Birgitta Olsson", "Karin Persson", "Ingrid Svensson", "Christina Gustafsson",
	"Marianne Pettersson", "Gunilla Jonsson", "Monica Jansson", "Barbro Hansson", "Annika Bengtsson",
	"Helena Lindqvist", "Inger Lindgren", "Ulla Axelsson", "Lena Berglund", "Carina Bergström",
	// Norwegian names
	"Ole Hansen", "Lars Johansen", "Erik Larsen", "Jan Andersen", "Per Pedersen",
	"Nils Nilsen", "Hans Olsen", "Magnus Kristiansen", "Karl Jacobsen", "Anders Jensen",
	"Knut Halvorsen", "Leif Haugen", "Thor Bakken", "Svein Solberg", "Bjørn Berg",
	"Øyvind Moen", "Geir Strand", "Trond Hagen", "Odd Løken", "Rune Brekke",
	"Anne Hansen", "Marie Johansen", "Kari Larsen", "Ingrid Andersen", "Marit Pedersen",
	"Berit Nilsen", "Astrid Olsen", "Liv Kristiansen", "Else Jacobsen", "Ragnhild Jensen",
	"Gerd Halvorsen", "Solveig Haugen", "Bente Bakken", "Heidi Solberg", "Hilde Berg",
	"Linda Moen", "Silje Strand", "Kristin Hagen", "Mette Løken", "Tone Brekke",
	// Finnish names
	"Juhani Korhonen", "Mikko Virtanen", "Matti Mäkinen", "Pekka Nieminen", "Timo Mäkelä",
	"Antti Hämäläinen", "Juha Laine", "Kari Heikkinen", "Heikki Koskinen", "Marko Järvinen",
	"Sami Lehtonen", "Petri Saarinen", "Jari Lahtinen", "Ville Niemi", "Markku Salonen",
	"Jarmo Heinonen", "Seppo Tuominen", "Vesa Hirvonen", "Ari Laitinen", "Hannu Mattila",
	"Maria Korhonen", "Anna Virtanen", "Liisa Mäkinen", "Pirjo Nieminen", "Leena Mäkelä",
	"Marja Hämäläinen", "Päivi Laine", "Sari Heikkinen", "Tarja Koskinen", "Tiina Järvinen",
	"Jaana Lehtonen", "Eija Saarinen", "Hanna Lahtinen", "Mari Niemi", "Johanna Salonen",
	"Laura Heinonen", "Riikka Tuominen", "Minna Hirvonen", "Elina Laitinen", "Kaisa Mattila",
	// Greek names
	"Georgios Papadopoulos", "Dimitrios Ioannou", "Konstantinos Nikolaou", "Ioannis Georgiou", "Nikolaos Vasileiou",
	"Christos Papadakis", "Panagiotis Alexiou", "Vasileios Antonopoulos", "Athanasios Christodoulou", "Michail Makris",
	"Spyridon Karakostas", "Evangelos Papanikolaou", "Anastasios Dimitriou", "Theodoros Konstantinou", "Andreas Angelopoulos",
	"Alexandros Economou", "Stefanos Vlachos", "Petros Karagiannis", "Eleftherios Sotiriou", "Emmanouil Papadimitriou",
	"Maria Papadopoulou", "Eleni Ioannou", "Aikaterini Nikolaou", "Vasiliki Georgiou", "Sofia Vasileiou",
	"Georgia Papadaki", "Dimitra Alexiou", "Anastasia Antonopoulou", "Christina Christodoulou", "Konstantina Makri",
	"Paraskevi Karakosta", "Ioanna Papanikolaou", "Evangelia Dimitriou", "Panagiota Konstantinou", "Ourania Angelopoulou",
	"Despoina Economou", "Styliani Vlachou", "Stavroula Karagianni", "Theodora Sotiriou", "Chrysoula Papadimitriou",
	// Additional mixed international names
	"Alex Thompson", "Morgan Davis", "Jordan Lee", "Taylor Martinez", "Casey Williams",
	"Riley Johnson", "Quinn Brown", "Avery Anderson", "Cameron Wilson", "Sydney Taylor",
	"Dakota Jones", "Parker Garcia", "Reese Miller", "Sawyer Robinson", "Drew Clark",
	"Phoenix Walker", "Skyler Hall", "Finley Young", "Rowan King", "Emery Scott",
	"Hiroki Tanaka", "Yusuke Sato", "Takumi Suzuki", "Ryo Watanabe", "Shun Yamamoto",
	"Kota Nakamura", "Yuma Kobayashi", "Sora Kato", "Haru Yoshida", "Soma Yamada",
	"Sakura Ito", "Aika Hashimoto", "Momoka Inoue", "Himari Kimura", "Kokoro Hayashi",
	"Miyu Shimizu", "Hina Yamazaki", "Riko Mori", "Rin Ikeda", "Yuna Fujita",
	"Wei Ming", "Zhi Qiang", "Yi Fan", "Jia Hui", "Xiao Long",
	"Tian Yu", "Hao Ran", "Zi Yang", "Yun Fei", "Chen Xi",
	"Xin Yi", "Meng Yao", "Yu Ting", "Si Han", "Zi Xuan",
	"Jia Xin", "Yi Nuo", "Ke Xin", "Yu Han", "Wen Jing",
	// European additional names
	"Alexander Schneider", "Maximilian Hoffmann", "Sebastian Wagner", "Lukas Bauer", "Jonas Schäfer",
	"Leon Hartmann", "Felix Weber", "Paul Fischer", "Niklas Schmitt", "Tim Braun",
	"Sophie Schneider", "Emma Hoffmann", "Mia Wagner", "Lea Bauer", "Hannah Schäfer",
	"Lena Hartmann", "Lina Weber", "Marie Fischer", "Julia Schmitt", "Laura Braun",
	"Hugo Bernard", "Gabriel Durand", "Raphaël Moreau", "Arthur Simon", "Lucas Michel",
	"Jules Lefebvre", "Théo Roux", "Mathis Fournier", "Nathan Girard", "Tom André",
	"Léa Bernard", "Chloé Durand", "Emma Moreau", "Manon Simon", "Camille Michel",
	"Inès Lefebvre", "Louise Roux", "Jade Fournier", "Zoé Girard", "Alice André",
	// Latin American names
	"Diego Fernández", "Sebastián Álvarez", "Matías Romero", "Santiago Ruiz", "Nicolás Torres",
	"Benjamín Castro", "Martín Ortiz", "Felipe Núñez", "Lucas Soto", "Daniel Mendoza",
	"Valentina Fernández", "Camila Álvarez", "Isabella Romero", "Sofía Ruiz", "Daniela Torres",
	"Martina Castro", "Catalina Ortiz", "Victoria Núñez", "Luciana Soto", "Emilia Mendoza",
	"Leonardo Morais", "Arthur Barbosa", "Heitor Cardoso", "Bernardo Nascimento", "Enzo Rocha",
	"Lorenzo Martins", "Miguel Carvalho", "Davi Araújo", "Samuel Melo", "Benjamin Nunes",
	"Helena Morais", "Alice Barbosa", "Laura Cardoso", "Sophia Nascimento", "Manuela Rocha",
	"Livia Martins", "Giovanna Carvalho", "Lara Araújo", "Antonella Melo", "Cecília Nunes",
	// Middle Eastern additional names
	"Amir Hosseini", "Reza Ahmadi", "Mohammad Hashemi", "Ali Tehrani", "Hossein Karimi",
	"Mehdi Shirazi", "Hamid Moradi", "Saeed Gholami", "Farhad Nazari", "Arash Rahimi",
	"Maryam Hosseini", "Zahra Ahmadi", "Fatemeh Hashemi", "Sara Tehrani", "Leila Karimi",
	"Nasrin Shirazi", "Parisa Moradi", "Shirin Gholami", "Mina Nazari", "Azadeh Rahimi",
	"Yosef Ben-David", "David Cohen", "Michael Levy", "Daniel Mizrahi", "Moshe Goldberg",
	"Eli Friedman", "Avi Shapiro", "Jonathan Katz", "Benjamin Klein", "Aaron Schwartz",
	"Sarah Ben-David", "Rachel Cohen", "Rebecca Levy", "Miriam Mizrahi", "Leah Goldberg",
	"Hannah Friedman", "Naomi Shapiro", "Ruth Katz", "Esther Klein", "Deborah Schwartz",
	// Southeast Asian names
	"Nguyen Van Minh", "Tran Duc Anh", "Le Quang Huy", "Pham Hoang Long", "Hoang Van Tuan",
	"Bui Thanh Dat", "Do Minh Khang", "Ngo Duc Thinh", "Vu Anh Dung", "Trinh Van Phuc",
	"Nguyen Thi Mai", "Tran Thi Lan", "Le Thi Huong", "Pham Thi Ngoc", "Hoang Thi Thao",
	"Bui Thi Linh", "Do Thi Hong", "Ngo Thi Hanh", "Vu Thi Thanh", "Trinh Thi Hoa",
	"Somchai Wongsuwan", "Prasert Srisuk", "Wichai Charoenpong", "Sompong Thammarat", "Nattapong Phetdee",
	"Pornthip Wongsuwan", "Siriporn Srisuk", "Wanida Charoenpong", "Kanittha Thammarat", "Sasithorn Phetdee",
	"Budi Santoso", "Agus Setiawan", "Eko Prasetyo", "Dedi Kurniawan", "Hendra Wijaya",
	"Sri Santoso", "Dewi Setiawan", "Siti Prasetyo", "Rina Kurniawan", "Maya Wijaya",
	// Additional names to reach 1000
	"Christopher Morgan", "Benjamin Foster", "Alexander Hayes", "Samuel Reed", "Nicholas Gray",
	"Jonathan Brooks", "Brandon Price", "Tyler Russell", "Zachary Hughes", "Aaron Ross",
	"Victoria Morgan", "Elizabeth Foster", "Madison Hayes", "Abigail Reed", "Olivia Gray",
	"Emily Brooks", "Hannah Price", "Isabella Russell", "Sophia Hughes", "Grace Ross",
	"Mateo Delgado", "Andrés Castillo", "Jorge Molina", "Ricardo Vega", "Eduardo Salazar",
	"Francisco Guerrero", "Alberto Medina", "Ramón Aguilar", "Julián Ramírez", "Ignacio Paredes",
	"Gabriela Delgado", "Lorena Castillo", "Adriana Molina", "Verónica Vega", "Mariana Salazar",
	"Carmen Guerrero", "Teresa Medina", "Angela Aguilar", "Fernanda Ramírez", "Alejandra Paredes",
	"Romain Duval", "Julien Fontaine", "Vincent Mercier", "Sébastien Morel", "Florian Lambert",
	"Yann Bonnet", "Mathieu Giraud", "Jérôme Rousseau", "Baptiste Gautier", "Quentin Boyer",
	"Amélie Duval", "Océane Fontaine", "Marion Mercier", "Pauline Morel", "Margot Lambert",
	"Charlotte Bonnet", "Anaïs Giraud", "Marine Rousseau", "Clara Gautier", "Axelle Boyer",
	"Liam Murphy", "Connor O'Brien", "Sean Kelly", "Cian Ryan", "Oisín Walsh",
	"Fionn Byrne", "Eoin McCarthy", "Darragh Fitzgerald", "Cathal O'Sullivan", "Shane Kennedy",
	"Aoife Murphy", "Ciara O'Brien", "Niamh Kelly", "Saoirse Ryan", "Caoimhe Walsh",
	"Aisling Byrne", "Orla McCarthy", "Róisín Fitzgerald", "Siobhán O'Sullivan", "Maeve Kennedy",
	"Viktor Novák", "Jakub Svoboda", "Martin Dvořák", "Tomáš Černý", "Petr Procházka",
	"Jiří Kučera", "Pavel Veselý", "Michal Horák", "Ondřej Marek", "David Němec",
	"Eva Nováková", "Jana Svobodová", "Marie Dvořáková", "Lucie Černá", "Petra Procházková",
	"Lenka Kučerová", "Markéta Veselá", "Tereza Horáková", "Kristýna Marková", "Veronika Němcová",
	"Matteo Ferrero", "Leonardo Fontana", "Gabriele Galli", "Filippo Marchetti", "Francesco Villa",
	"Alessandro Fabbri", "Nicola Rinaldi", "Giacomo Orlando", "Tommaso Barbieri", "Andrea Mariani",
	"Giulia Ferrero", "Martina Fontana", "Federica Galli", "Chiara Marchetti", "Elena Villa",
	"Alessia Fabbri", "Sofia Rinaldi", "Giorgia Orlando", "Aurora Barbieri", "Greta Mariani",
	"Jens Andersen", "Morten Christensen", "Kasper Madsen", "Emil Thomsen", "Frederik Nielsen",
	"Søren Larsen", "Christian Sørensen", "Mathias Rasmussen", "Jonas Jørgensen", "Simon Petersen",
	"Mette Andersen", "Lise Christensen", "Cecilie Madsen", "Sofie Thomsen", "Emma Nielsen",
	"Julie Larsen", "Christina Sørensen", "Camilla Rasmussen", "Laura Jørgensen", "Line Petersen",
	"Andrei Ionescu", "Mihai Popescu", "Alexandru Popa", "Ion Stoica", "Cristian Marinescu",
	"George Dumitrescu", "Adrian Munteanu", "Vlad Gheorghe", "Dan Rusu", "Florin Stefan",
	"Maria Ionescu", "Elena Popescu", "Ana Popa", "Ioana Stoica", "Andreea Marinescu",
	"Alexandra Dumitrescu", "Cristina Munteanu", "Diana Gheorghe", "Raluca Rusu", "Alina Stefan",
	"Márton Szabó", "Bence Tóth", "Dániel Kovács", "Levente Horváth", "Ádám Varga",
	"Gergő Kiss", "Máté Nagy", "Zoltán Balogh", "Balázs Molnár", "Kristóf Farkas",
	"Eszter Szabó", "Boglárka Tóth", "Réka Kovács", "Lilla Horváth", "Zsófia Varga",
	"Dóra Kiss", "Hanna Nagy", "Virág Balogh", "Nóra Molnár", "Luca Farkas",
}
