// Code generated by MockGen. DO NOT EDIT.
// Source: internal/system/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/system/service.go -destination=internal/system/mock_service_test.go -package=system Service
//

// Package system is a generated GoMock package.
package system

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetSyntheticMode mocks base method.
func (m *MockService) GetSyntheticMode(ctx context.Context) (*SyntheticModeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyntheticMode", ctx)
	ret0, _ := ret[0].(*SyntheticModeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyntheticMode indicates an expected call of GetSyntheticMode.
func (mr *MockServiceMockRecorder) GetSyntheticMode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyntheticMode", reflect.TypeOf((*MockService)(nil).GetSyntheticMode), ctx)
}

// SetSyntheticMode mocks base method.
func (m *MockService) SetSyntheticMode(ctx context.Context, enabled bool) (*SyntheticModeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSyntheticMode", ctx, enabled)
	ret0, _ := ret[0].(*SyntheticModeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSyntheticMode indicates an expected call of SetSyntheticMode.
func (mr *MockServiceMockRecorder) SetSyntheticMode(ctx, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSyntheticMode", reflect.TypeOf((*MockService)(nil).SetSyntheticMode), ctx, enabled)
}
