// Code generated by MockGen. DO NOT EDIT.
// Source: internal/system/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/system/repository.go -destination=internal/system/mock_repository_test.go -package=system Repository
//

// Package system is a generated GoMock package.
package system

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetSyntheticMode mocks base method.
func (m *MockRepository) GetSyntheticMode(ctx context.Context) (*SyntheticModeConfig, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyntheticMode", ctx)
	ret0, _ := ret[0].(*SyntheticModeConfig)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSyntheticMode indicates an expected call of GetSyntheticMode.
func (mr *MockRepositoryMockRecorder) GetSyntheticMode(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyntheticMode", reflect.TypeOf((*MockRepository)(nil).GetSyntheticMode), ctx)
}

// SetSyntheticMode mocks base method.
func (m *MockRepository) SetSyntheticMode(ctx context.Context, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSyntheticMode", ctx, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSyntheticMode indicates an expected call of SetSyntheticMode.
func (mr *MockRepositoryMockRecorder) SetSyntheticMode(ctx, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSyntheticMode", reflect.TypeOf((*MockRepository)(nil).SetSyntheticMode), ctx, enabled)
}
